feat(cmd): add build command (#38)
* feat(build/mitre): add mitre

* feat(build/nvd): add nvd

* feat(build/epss): add epss

* feat(build/msf): add msf

* feat(build/kev): add kev

* feat(build/exploitdb): add exploitdb

* feat(build/exploit): add githubrepos

* feat(build/exploit): add inthewild

* feat(build/exploit): add trickest

* feat(build/jvn): add jvn

* feat(build/alma): add alma

* chore(build/nvd): omitempty

* feat(build/alpine): add alpine

* chore(build/alpine): set title and remove invalid cve

* chore(fetch): add template

* chore(ci): update github actions

* feat(build/amazon): add amazon

* feat(build/arch): add arch

* feat(build/debian): add debian security tracker

* chore(build): add template

* feat(build/debian): add debian oval

* feat(build/freebsd): add freebsd

* chore(cpe): use operator and version

* feat(build/oracle): add oracle

* feat(build/redhat): add redhat

* chore: move log position and typo

* feat(fetch/suse): use indexof

* feat(build/suse): add suse oval

* feat(build/suse): add suse cvrf

* feat(build/ubuntu): add ubuntu oval

* feat(build/ubuntu): add ubuntu security tracker

* chore: add flag

* chore(ci): udpate github actions

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,7 +1,7 @@
 name: Update vuls-data
 on:
   schedule:
-    - cron: '0 * 1-31/2 * *'
+    - cron: '0 */12 * * *'
   workflow_dispatch:
 
 jobs:
@@ -281,13 +281,23 @@ jobs:
       #     git push origin HEAD:main
       #     cd ..
 
-      # - name: fetch other cti
+      # - name: fetch other attack
       #   if: ${{ success() || failure() }}
       #   run: |
-      #     vuls-data-update fetch other cti
+      #     vuls-data-update fetch other attack
       #     cd source
-      #     git add cti
-      #     git commit --allow-empty -m "update cti"
+      #     git add attack
+      #     git commit --allow-empty -m "update attack"
+      #     git push origin HEAD:main
+      #     cd ..
+
+      # - name: fetch other capec
+      #   if: ${{ success() || failure() }}
+      #   run: |
+      #     vuls-data-update fetch other capec
+      #     cd source
+      #     git add capec
+      #     git commit --allow-empty -m "update capec"
       #     git push origin HEAD:main
       #     cd ..
 
@@ -361,15 +371,15 @@ jobs:
           git push origin HEAD:main
           cd ..
 
-      # - name: fetch other nvd
-      #   if: ${{ success() || failure() }}
-      #   run: |
-      #     vuls-data-update fetch other nvd
-      #     cd source
-      #     git add nvd
-      #     git commit --allow-empty -m "update nvd"
-      #     git push origin HEAD:main
-      #     cd ..
+      - name: fetch other nvd
+        if: ${{ success() || failure() }}
+        run: |
+          vuls-data-update fetch other nvd
+          cd source
+          git add nvd
+          git commit --allow-empty -m "update nvd"
+          git push origin HEAD:main
+          cd ..
 
       - name: update source submodule commit
         run: |
@@ -378,4 +388,39 @@ jobs:
           git commit -m "chore(ci): update source submodule"
           git push
 
-  # build:
+  build:
+     name: build vuls-data-source
+     runs-on: ubuntu-latest
+     if: ${{ always() }}
+     needs: fetch
+     steps:
+      - name: set Git config
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.GH_PAT }}
+          submodules: recursive
+
+      - name: update source and output submodule
+        run: git submodule update --remote --recursive source output
+
+      - name: Set up Go 1.x
+        uses: actions/setup-go@v3
+        with:
+          go-version-file: 'go.mod'
+
+      - name: go install
+        run: go install ./cmd/vuls-data-update
+
+      - name: build
+        run: |
+          vuls-data-update build
+          cd output
+          git add vulnerability cpe os
+          git commit --allow-empty -m "update vulnerability"
+          git push origin HEAD:main
+          cd ..
