feat(ci): add fedora

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -231,7 +231,10 @@ jobs:
       - name: Commit
         run: |
           cd vuls-data-raw-${{ matrix.target }}
-          git restore $(git ls-files --deleted | grep -v ${{ matrix.year }}/)
+          deleted=$(git ls-files --deleted | grep -v ${{ matrix.year }}/ || [[ $? == 1 ]])
+          if [[ -n ${deleted} ]]; then
+            git restore ${deleted}
+          fi
           if [[ -n $(git status --porcelain) ]]; then
             git add ${{ matrix.year }}
             git commit -m "update ${{ matrix.year }}"
@@ -376,3 +379,86 @@ jobs:
             git commit -m "update"
             git push
           fi
+
+  fetch-fedora-release:
+    name: fetch fedora release
+    runs-on: ubuntu-latest
+    outputs:
+      release: ${{ steps.fetch.outputs.release }}
+    steps:
+      - name: Fetch Release
+        id: fetch
+        run: |
+          curl --parallel --parallel-immediate  --parallel-max 3 --retry 10 -o "#1.json" "https://bodhi.fedoraproject.org/releases/?page=[1-$(curl -s --retry 10 "https://bodhi.fedoraproject.org/releases/?page=1&rows_per_page=10" | jq .pages)]&rows_per_page=10"
+          echo "release=$(cat *.json | jq -r '.releases[].name' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+
+  fetch-fedora:
+    name: fetch vuls-data-raw-fedora ${{ matrix.release }}
+    runs-on: ubuntu-latest
+    needs: fetch-fedora-release
+    strategy:
+      fail-fast: false
+      matrix:
+        release: ${{ fromJson(needs.fetch-fedora-release.outputs.release) }}
+    steps:
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v4
+
+      - name: Set up Go 1.x
+        uses: actions/setup-go@v4
+        with:
+          go-version-file: "go.mod"
+
+      - name: go install
+        run: go install ./cmd/vuls-data-update
+
+      - uses: actions/create-github-app-token@v1
+        id: app-token
+        with:
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.PRIVATE_KEY }}
+          owner: vulsio
+          repositories: "vuls-data-raw-fedora"
+
+      - name: Check out fetch data repository
+        uses: actions/checkout@v4
+        with:
+          repository: vulsio/vuls-data-raw-fedora
+          path: vuls-data-raw-fedora
+          token: ${{ steps.app-token.outputs.token }}
+
+      - name: Fetch
+        run: vuls-data-update fetch fedora --dir vuls-data-raw-fedora ${{ matrix.release }} --retry 10
+
+      - name: Split Large Files
+        run: find vuls-data-raw-fedora -name "*.json" -size +50M | xargs -I {} sh -c "split -a 3 -d -b 50m {} {}. && rm {}"
+
+      - name: set Git config
+        run: |
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+
+      - name: Commit
+        run: |
+          cd vuls-data-raw-fedora
+          deleted=$(git ls-files --deleted | grep -v ${{ matrix.release }}/ || [[ $? == 1 ]])
+          if [[ -n ${deleted} ]]; then
+            git restore ${deleted}
+          fi
+          if [[ -n $(git status --porcelain) ]]; then
+            git add ${{ matrix.release }}
+            git commit -m "update ${{ matrix.release }}"
+          fi
+
+      - name: Push
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 10
+          max_attempts: ${{ strategy.job-total }}
+          on_retry_command: |
+            cd vuls-data-raw-fedora
+            git pull --rebase
+          command: |
+            cd vuls-data-raw-fedora
+            git push
+    
